name: Deploy to GitHub Pages

on:
  push:
    branches: [ feature/main ] 
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Export static files
        run: |
          mkdir -p out/_next/static
          cp -R .next/static out/_next/static || true
          cp -R public out/ || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true 